console.log("Product.js Loaded");
const products = [
  // ===== ELECTRONICS (1-15) =====
  { id: 1, name: "Pro Laptop", price: 999, category: "Electronic", image: "images/laptop.jpg" },
  { id: 2, name: "Smart Phone", price: 699, category: "Electronic", image: "images/phone.jpg" },
  { id: 3, name: "Wireless Headphones", price: 199, category: "Electronic", image: "images/headphones.jpg" },
  { id: 4, name: "Smart Watch", price: 249, category: "Electronic", image: "images/watch.jpg" },
  { id: 5, name: "Bluetooth Speaker", price: 89, category: "Electronic", image: "images/speaker.jpg" },
  { id: 6, name: "4K Monitor", price: 350, category: "Electronic", image: "images/monitor.jpg" },
  { id: 7, name: "Mechanical Keyboard", price: 120, category: "Electronic", image: "images/keyboard.jpg" },
  { id: 8, name: "Gaming Mouse", price: 60, category: "Electronic", image: "images/mouse.jpg" },
  { id: 9, name: "Tablet Pro", price: 599, category: "Electronic", image: "images/tablet.jpg" },
  { id: 10, name: "DSLR Camera", price: 850, category: "Electronic", image: "images/camera.jpg" },
  { id: 11, name: "External SSD", price: 130, category: "Electronic", image: "images/ssd.jpg" },
  { id: 12, name: "Noise Cancelling Earbuds", price: 150, category: "Electronic", image: "images/earbuds.jpg" },
  { id: 13, name: "Smart Home Hub", price: 99, category: "Electronic", image: "images/hub.jpg" },
  { id: 14, name: "Webcam HD", price: 75, category: "Electronic", image: "images/webcam.jpg" },
  { id: 15, name: "Power Bank", price: 45, category: "Electronic", image: "images/powerbank.jpg" },

  // ===== FASHION (16-30) =====
  { id: 16, name: "Running Shoes", price: 120, category: "Fashion", image: "images/shoes.jpg" },
  { id: 17, name: "Leather Jacket", price: 250, category: "Fashion", image: "images/jacket.jpg" },
  { id: 18, name: "Denim Jeans", price: 65, category: "Fashion", image: "images/jeans.jpg" },
  { id: 19, name: "Cotton T-Shirt", price: 25, category: "Fashion", image: "images/tshirt.jpg" },
  { id: 20, name: "Designer Sunglasses", price: 180, category: "Fashion", image: "images/sunglasses.jpg" },
  { id: 21, name: "Winter Coat", price: 190, category: "Fashion", image: "images/coat.jpg" },
  { id: 22, name: "Formal Shirt", price: 45, category: "Fashion", image: "images/shirt.jpg" },
  { id: 23, name: "Canvas Sneakers", price: 55, category: "Fashion", image: "images/sneakers.jpg" },
  { id: 24, name: "Silk Scarf", price: 35, category: "Fashion", image: "images/scarf.jpg" },
  { id: 25, name: "Wrist Watch Gold", price: 320, category: "Fashion", image: "images/goldwatch.jpg" },
  { id: 26, name: "Baseball Cap", price: 20, category: "Fashion", image: "images/cap.jpg" },
  { id: 27, name: "Woolen Sweater", price: 70, category: "Fashion", image: "images/sweater.jpg" },
  { id: 28, name: "Leather Belt", price: 40, category: "Fashion", image: "images/belt.jpg" },
  { id: 29, name: "Evening Dress", price: 140, category: "Fashion", image: "images/dress.jpg" },
  { id: 30, name: "Backpack", price: 85, category: "Fashion", image: "images/backpack.jpg" },

  // ===== BOOKS (31-45) =====
  { id: 31, name: "JavaScript Guide", price: 30, category: "Books", image: "images/jsbook.jpg" },
  { id: 32, name: "The Great Gatsby", price: 15, category: "Books", image: "images/gatsby.jpg" },
  { id: 33, name: "Python Crash Course", price: 35, category: "Books", image: "images/python.jpg" },
  { id: 34, name: "History of Time", price: 22, category: "Books", image: "images/history.jpg" },
  { id: 35, name: "Mystery at Midnight", price: 18, category: "Books", image: "images/mystery.jpg" },
  { id: 36, name: "Science Fiction Anthology", price: 25, category: "Books", image: "images/scifi.jpg" },
  { id: 37, name: "Cooking Masterclass", price: 40, category: "Books", image: "images/cooking.jpg" },
  { id: 38, name: "The Art of War", price: 12, category: "Books", image: "images/artofwar.jpg" },
  { id: 39, name: "Digital Marketing 101", price: 28, category: "Books", image: "images/marketing.jpg" },
  { id: 40, name: "Atlas of the World", price: 50, category: "Books", image: "images/atlas.jpg" },
  { id: 41, name: "The Alchemist", price: 14, category: "Books", image: "images/alchemist.jpg" },
  { id: 42, name: "Space Exploration", price: 32, category: "Books", image: "images/space.jpg" },
  { id: 43, name: "Photography Basics", price: 27, category: "Books", image: "images/photobook.jpg" },
  { id: 44, name: "Philosophy 101", price: 20, category: "Books", image: "images/philosophy.jpg" },
  { id: 45, name: "Graphic Design Rules", price: 45, category: "Books", image: "images/designbook.jpg" },

  // ===== HOME DECORATION (46-60) =====
  { id: 46, name: "Ceramic Vase", price: 45, category: "Home Decoration", image: "images/vase.jpg" },
  { id: 47, name: "Wall Mirror", price: 110, category: "Home Decoration", image: "images/mirror.jpg" },
  { id: 48, name: "Scented Candles", price: 25, category: "Home Decoration", image: "images/candles.jpg" },
  { id: 49, name: "Throw Blanket", price: 55, category: "Home Decoration", image: "images/blanket.jpg" },
  { id: 50, name: "Table Lamp", price: 80, category: "Home Decoration", image: "images/lamp.jpg" },
  { id: 51, name: "Abstract Wall Art", price: 150, category: "Home Decoration", image: "images/art.jpg" },
  { id: 52, name: "Indoor Plant Pot", price: 30, category: "Home Decoration", image: "images/pot.jpg" },
  { id: 53, name: "Decorative Pillows", price: 40, category: "Home Decoration", image: "images/pillows.jpg" },
  { id: 54, name: "Floor Rug", price: 220, category: "Home Decoration", image: "images/rug.jpg" },
  { id: 55, name: "Clock Minimalist", price: 65, category: "Home Decoration", image: "images/clock.jpg" },
  { id: 56, name: "Bookends Metal", price: 35, category: "Home Decoration", image: "images/bookends.jpg" },
  { id: 57, name: "Floating Shelves", price: 70, category: "Home Decoration", image: "images/shelves.jpg" },
  { id: 58, name: "Photo Frame Set", price: 45, category: "Home Decoration", image: "images/frames.jpg" },
  { id: 59, name: "String Lights", price: 20, category: "Home Decoration", image: "images/lights.jpg" },
  { id: 60, name: "Coaster Set", price: 15, category: "Home Decoration", image: "images/coasters.jpg" },

  // ===== SPORTS (61-75) =====
  { id: 61, name: "Football", price: 25, category: "Sports", image: "images/football.jpg" },
  { id: 62, name: "Yoga Mat", price: 35, category: "Sports", image: "images/yogamat.jpg" },
  { id: 63, name: "Tennis Racket", price: 140, category: "Sports", image: "images/racket.jpg" },
  { id: 64, name: "Dumbbell Set", price: 120, category: "Sports", image: "images/dumbbells.jpg" },
  { id: 65, name: "Basketball", price: 30, category: "Sports", image: "images/basketball.jpg" },
  { id: 66, name: "Skipping Rope", price: 15, category: "Sports", image: "images/rope.jpg" },
  { id: 67, name: "Cycling Helmet", price: 85, category: "Sports", image: "images/helmet.jpg" },
  { id: 68, name: "Swim Goggles", price: 22, category: "Sports", image: "images/goggles.jpg" },
  { id: 69, name: "Punching Bag", price: 160, category: "Sports", image: "images/punchbag.jpg" },
  { id: 70, name: "Cricket Bat", price: 200, category: "Sports", image: "images/bat.jpg" },
  { id: 71, name: "Hiking Poles", price: 45, category: "Sports", image: "images/poles.jpg" },
  { id: 72, name: "Stopwatch", price: 20, category: "Sports", image: "images/stopwatch.jpg" },
  { id: 73, name: "Resistance Bands", price: 25, category: "Sports", image: "images/bands.jpg" },
  { id: 74, name: "Sports Water Bottle", price: 18, category: "Sports", image: "images/bottle.jpg" },
  { id: 75, name: "Badminton Shuttlecocks", price: 12, category: "Sports", image: "images/shuttle.jpg" }
];